# Generated by Django 3.0.3 on 2020-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default='2020-01-01 00:00', verbose_name='data published'),
            preserve_default=False,
        ),
    ]
